# FIFA World Cups Analysis

In order to better place my bets for the world cup games 2018, I want to look at how the games typically ended in previous world cups to complement the knowledge of bookie odds with past game stats.

Questions to answer:

1. How did the group games end most often?
1. If the group games ended on a draw, what was the most frequent score tie?

In [1]:
import pandas as pd

In [2]:
wc14 = pd.read_json("../data_acquisition/data/worldcup2014.json")
wc14

,away_team,game_number_within_game_type,game_type,group,home_team,penalties_home_vs_away,score_home_vs_away,total_game_index
0,Croatia,1,group,Group A,Brazil,None,3-1,0
1,Cameroon,2,group,Group A,Mexico,None,1-0,1
2,Mexico,3,group,Group A,Brazil,None,0-0,2
3,Croatia,4,group,Group A,Cameroon,None,0-4,3
4,Brazil,5,group,Group A,Cameroon,None,1-4,4
5,Mexico,6,group,Group A,Croatia,None,1-3,5
6,Netherlands,1,group,Group B,Spain,None,1-5,6
7,Australia,2,group,Group B,Chile,None,3-1,7
8,Netherlands,3,group,Group B,Australia,None,2-3,8
9,Chile,4,group,Group B,Spain,None,0-2,9
10,Spain,5,group,Group B,Australia,None,0-3,10
11,Chile,6,group,Group B,Netherlands,None,2-0,11
12,Greece,1,group,Group C,Colombia,None,3-0,12
13,Japan,2,group,Group C,Ivory Coast,None,2-1,13
14,Ivory Coast,3,group,Group C,Colombia,None,2-1,14
15,Greece,4,group,Group C,Japan,None,0-0,15
16,Colombia,5,group,Group C,Japan,None,1-4,16
17,Ivory Coast,6,group,Group C,Greece,None,2-1,17
18,Costa Rica,1,group,Group D,Uruguay,None,1-3,18
19,Italy,2,group,Group D,England,None,1-2,19
20,England,3,group,Group D,Uruguay,None,2-1,20
21,Costa Rica,4,group,Group D,Italy,None,0-1,21
22,Uruguay,5,group,Group D,Italy,None,0-1,22
23,England,6,group,Group D,Costa Rica,None,0-0,23
24,Ecuador,1,group,Group E,Switzerland,None,2-1,24
25,Honduras,2,group,Group E,France,None,3-0,25
26,France,3,group,Group E,Switzerland,None,2-5,26
27,Ecuador,4,group,Group E,Honduras,None,1-2,27
28,Switzerland,5,group,Group E,Honduras,None,0-3,28
29,France,6,group,Group E,Ecuador,None,0-0,29
...,...,...,...,...,...,...,...,...
34,Argentina,5,group,Group F,Nigeria,None,2-3,34
35,Iran,6,group,Group F,Bosnia and Herzegovina,None,3-1,35
36,Portugal,1,group,Group G,Germany,None,4-0,36
37,United States,2,group,Group G,Ghana,None,1-2,37
38,Ghana,3,group,Group G,Germany,None,2-2,38
39,Portugal,4,group,Group G,United States,None,2-2,39
40,Germany,5,group,Group G,United States,None,0-1,40
41,Ghana,6,group,Group G,Portugal,None,2-1,41
42,Algeria,1,group,Group H,Belgium,None,2-1,42
43,South Korea,2,group,Group H,Russia,None,1-1,43
44,Russia,3,group,Group H,Belgium,None,1-0,44
45,Algeria,4,group,Group H,South Korea,None,2-4,45
46,Belgium,5,group,Group H,South Korea,None,0-1,46
47,Russia,6,group,Group H,Algeria,None,1-1,47
48,Chile,1,round of 16,None,Brazil,3-2,1-1,48
49,Uruguay,2,round of 16,None,Colombia,None,2-0,49
50,Mexico,3,round of 16,None,Netherlands,None,2-1,50
51,Greece,4,round of 16,None,Costa Rica,5-3,1-1,51
52,Nigeria,5,round of 16,None,France,None,2-0,52
53,Algeria,6,round of 16,None,Germany,None,2-1,53
54,Switzerland,7,round of 16,None,Argentina,None,1-0,54
55,United States,8,round of 16,None,Belgium,None,2-1,55
56,Germany,1,quarter final,None,France,None,0-1,56
57,Colombia,2,quarter final,None,Brazil,None,2-1,57
58,Belgium,3,quarter final,None,Argentina,None,1-0,58
59,Costa Rica,4,quarter final,None,Netherlands,4-3,0-0,59
60,Germany,1,semi final,None,Brazil,None,1-7,60
61,Argentina,2,semi final,None,Netherlands,2-4,0-0,61
62,Netherlands,1,third place play-off,None,Brazil,None,0-3,62
63,Argentina,1,final,None,Germany,None,1-0,63

# How did the group games end most often?

In [3]:
cnts = wc14.loc[wc14.game_type == "group"]["score_home_vs_away"].value_counts()
freq = pd.concat([cnts, cnts/cnts.sum()], axis=1)
freq.columns = ["abs_freq", "rel_freq"]
freq

     abs_freq  rel_freq
2-1         8  0.166667
0-0         5  0.104167
0-1         4  0.083333
1-0         4  0.083333
1-2         3  0.062500
3-1         3  0.062500
1-3         2  0.041667
1-4         2  0.041667
2-2         2  0.041667
3-0         2  0.041667
2-3         2  0.041667
0-3         2  0.041667
1-1         2  0.041667
4-0         1  0.020833
0-2         1  0.020833
1-5         1  0.020833
2-5         1  0.020833
2-4         1  0.020833
2-0         1  0.020833
0-4         1  0.020833

8 games of 48 games of the group stage, i.e. 16.6% ended on 2-1, while 5 games (10%) ended on 0-0.

??? 2-1 and 1-2 are different results - combine them?

# If the group games ended on a draw, what was the most frequent score tie?

??? I need to preprocess the data to add fields indicating whether it is a draw and splitting the score string into separate fields